name: ImprovedFactions
version: '${project.version}'
main: io.github.toberocat.improvedfactions.ImprovedFactionsPlugin
api-version: '1.18'
depend: [ GuiEngine, RunarMetricStats ]
softdepend: [ PlaceholderAPI ]
authors: ["Tobero", "Vakea"]
commands:
  factions:
    aliases: [ "f", "fac", "faction" ]
permissions:
  factions.updatechecker:
    default: op
  factions:
    default: true
  factions.info:
    default: true
  factions.create:
    default: true
  factions.join:
    default: true
  factions.delete:
    default: true
  factions.icon:
    default: true
  factions.invite:
    default: true
  factions.invites:
    default: true
  factions.invitediscard:
    default: true
  factions.inviteaccept:
    default: true
  factions.leave:
    default: true
  factions.rename:
    default: true
  factions.claim:
    default: true
  factions.unclaim:
    default: true
  factions.help:
    default: true
  factions.rank:
    default: true
  factions.rank.assign:
    default: true
  factions.rank.create:
    default: true
  factions.rank.default:
    default: true
  factions.rank.delete:
    default: true
  factions.rank.edit:
    default: true
  factions.rank.set:
    default: true
  factions.kick:
    default: true
  factions.ban:
    default: true
  factions.unban:
    default: true
  factions.members:
    default: true
  factions.transferowner:
    default: true
  factions.power:
    default: true
  factions.zone:
    default: op
  factions.zone.claim:
    default: op
  factions.zone.unclaim:
    default: op
  factions.reload:
    default: op